trigger:
- main

pool: 
  name: MacBookAgent

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x.x'  # Use the version of .NET Core 8 you have installed

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build $(solution) --configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)
  displayName: 'Build solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --logger trx --results-directory $(Common.TestResultsDirectory)
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    testRunTitle: 'Test Results'

