trigger:
- main

pool: 
  name: SkyNet

variables:
  solution: 'personalStaticWebSite.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.204'  # Use the version of .NET Core 8 you have installed

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build $(solution) --configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)
  displayName: 'Build solution'

